import { InventoryItem, LocationData, User } from './types';

export const LOCATIONS: LocationData[] = [
  {
    id: 'warehouse',
    name: 'Warehouse',
    description: 'Main storage facility for bulk items and raw materials.',
    icon: 'warehouse',
    type: 'central'
  },
  {
    id: 'mammal',
    name: 'Mammal',
    description: 'Production and processing unit.',
    icon: 'factory',
    type: 'central'
  }
];

export const INITIAL_INVENTORY: Record<string, InventoryItem[]> = {
  warehouse: [
    { id: '1', nameEn: 'Arabica Coffee Beans', nameAr: 'بن قهوة أرابيكا', description: 'High-quality roasted arabica beans from Ethiopia.', category: 'Raw Material', quantity: 500, unit: 'kg', minThreshold: 100, lastUpdated: '2023-10-25' },
    { id: '2', nameEn: 'Paper Cups (12oz)', nameAr: 'أكواب ورقية (12 أونصة)', description: 'Disposable eco-friendly paper cups for hot beverages.', category: 'Packaging', quantity: 5000, unit: 'pcs', minThreshold: 1000, lastUpdated: '2023-10-24' },
    { id: '3', nameEn: 'Caramel Syrup', nameAr: 'شراب الكراميل', description: 'Premium caramel flavoring for coffee and lattes.', category: 'Ingredients', quantity: 45, unit: 'bottles', minThreshold: 20, lastUpdated: '2023-10-20' },
    { id: '4', nameEn: 'Whole Milk (UHT)', nameAr: 'حليب كامل الدسم (معقم)', description: 'Long-life full cream milk for steaming.', category: 'Ingredients', quantity: 200, unit: 'liters', minThreshold: 50, lastUpdated: '2023-10-26' },
    { id: '5', nameEn: 'Sugar Sticks', nameAr: 'أصابع سكر', description: 'Individual 5g white sugar portions.', category: 'Ingredients', quantity: 10000, unit: 'pcs', minThreshold: 2000, lastUpdated: '2023-10-15' },
  ],
  mammal: [
    { id: '101', nameEn: 'Arabica Coffee Beans', nameAr: 'بن قهوة أرابيكا', description: 'Daily supply of roasted beans for production.', category: 'Raw Material', quantity: 20, unit: 'kg', minThreshold: 50, lastUpdated: '2023-10-26' },
    { id: '102', nameEn: 'Paper Cups (12oz)', nameAr: 'أكواب ورقية (12 أونصة)', description: 'Current batch of serving cups.', category: 'Packaging', quantity: 150, unit: 'pcs', minThreshold: 200, lastUpdated: '2023-10-26' },
    { id: '103', nameEn: 'Vanilla Syrup', nameAr: 'شراب الفانيليا', description: 'Sweet vanilla extract for signature drinks.', category: 'Ingredients', quantity: 5, unit: 'bottles', minThreshold: 2, lastUpdated: '2023-10-25' },
    { id: '104', nameEn: 'Fresh Milk', nameAr: 'حليب طازج', description: 'Locally sourced fresh milk for latte art.', category: 'Ingredients', quantity: 12, unit: 'liters', minThreshold: 10, lastUpdated: '2023-10-26' },
    { id: '105', nameEn: 'Chocolate Sauce', nameAr: 'صلصة الشوكولاتة', description: 'Rich dark chocolate syrup for mochas.', category: 'Ingredients', quantity: 8, unit: 'bottles', minThreshold: 3, lastUpdated: '2023-10-22' },
  ]
};

export const INITIAL_USERS: User[] = [
  { id: '1', username: 'admin', password: '123', name: 'System Administrator', role: 'admin' },
  { id: '2', username: 'warehouse', password: '123', name: 'Main Supervisor', role: 'warehouse_manager' },
  { id: '3', username: 'employee', password: '123', name: 'Mammal Staff', role: 'mammal_employee' },
];

export const TRANSLATIONS = {
  en: {
    title: "Dawar Saada",
    subtitle: "Inventory Management System",
    username: "Username",
    usernamePlaceholder: "Enter username",
    password: "Password",
    passwordPlaceholder: "Enter password",
    login: "Sign In",
    invalidCredentials: "Invalid username or password",
    copyright: "© 2024 Dawar Saada. All rights reserved.",
    selectLocation: "Select Location",
    selectLocationSub: "Select a location to manage inventory",
    accessInventory: "Access Inventory",
    warehouse: "Warehouse",
    mammal: "Mammal",
    warehouseDesc: "Main storage facility for bulk items and raw materials.",
    mammalDesc: "Production and processing unit.",
    items: "Items",
    totalItems: "Total Items",
    lowStockAlert: "Low Stock Alert",
    aiInsights: "AI Insights",
    searchPlaceholder: "Search items...",
    filter: "Filter",
    addItem: "Add Item",
    itemName: "Item Name",
    itemNameEn: "Name (English)",
    itemNameAr: "Name (Arabic)",
    itemNameEnPlaceholder: "e.g., Arabica Beans",
    itemNameArPlaceholder: "مثال: بن أرابيكا",
    description: "Description",
    descriptionPlaceholder: "Enter detailed item description...",
    category: "Category",
    stockLevel: "Stock Level",
    status: "Status",
    lastUpdated: "Last Updated",
    actions: "Actions",
    inStock: "In Stock",
    lowStock: "Low Stock",
    noItemsFound: "No items found matching",
    actionNeeded: "Action needed",
    restockSuggested: "Restock suggested",
    stockHealthy: "Stock healthy",
    smartAssistant: "Smart Assistant",
    poweredBy: "Powered by Gemini",
    askAI: "Ask AI",
    askPlaceholder: "Ask about inventory...",
    welcomeMessage: "Hello! I'm your inventory assistant for",
    howHelp: "How can I help you today?",
    cantGenerate: "I couldn't generate a response at this time.",
    errorOccurred: "Sorry, I encountered an error while analyzing the inventory.",
    logout: "Logout",
    new: "new",
    adminDashboard: "Admin Dashboard",
    users: "Users",
    transactions: "Transactions",
    createUser: "Create User",
    editUser: "Edit User",
    updateUser: "Update User",
    role: "Role",
    fullName: "Full Name",
    saveUser: "Save User",
    cancel: "Cancel",
    transferStock: "Transfer Stock",
    from: "From",
    to: "To",
    quantity: "Quantity",
    submitTransfer: "Submit Transfer",
    selectItem: "Select Item",
    transferSuccess: "Transfer successful",
    insufficientStock: "Insufficient stock",
    date: "Date",
    performedBy: "Performed By",
    delete: "Delete",
    edit: "Edit",
    viewLogs: "View Logs",
    branch_manager: "Branch Manager",
    warehouse_manager: "Manager",
    mammal_employee: "Employee",
    admin: "Administrator",
    dailyLog: "Daily Log",
    recordUsage: "Record Usage",
    recordReceive: "Record Receiving",
    usageDesc: "Log items consumed in daily operations",
    receiveDesc: "Log items received from suppliers",
    submit: "Submit",
    type: "Type",
    transfer: "Transfer",
    usage: "Usage",
    receive: "Receive",
    notes: "Notes (Optional)",
    notesPlaceholder: "Add any additional details...",
    addToTransfer: "Add to List",
    transferList: "Items to Transfer",
    remove: "Remove",
    noItemsInList: "No items added to transfer list yet.",
    incomingShipments: "Incoming Shipments",
    confirmReceive: "Receive Stock",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
    receiveSuccess: "Stock received successfully",
    incomingDesc: "Items transferred from other locations waiting for your confirmation.",
    inventory: "Inventory",
    locationType: "Location Type",
    central: "Central",
    branch: "Branch",
    branchName: "Branch Name",
    branchCode: "Branch Code",
    branchCodePlaceholder: "e.g., BR001",
    branchNamePlaceholder: "e.g., Downtown Branch",
    addItemTitle: "Add New Item",
    initialQty: "Initial Quantity",
    minThreshold: "Min Threshold",
    unit: "Unit",
    unitPlaceholder: "e.g., kg, pcs, box",
    thresholdDesc: "Alert when stock falls below this amount",
    manageLocation: "Manage Inventory",
    currentStock: "Current Stock List",
    exportPDF: "Export PDF",
    exportExcel: "Export Excel",
    centralLocations: "Central Locations",
    branchLocations: "Branch Locations",
    branches: "Branches",
    confirm: "Confirm",
    used: "Used",
    smartUpload: "Smart Upload",
    confirmTransferPdf: "Confirm Transfer (From PDF)",
    noOtherLocations: "No other locations available",
    qtyGreaterZero: "Quantity must be greater than 0",
    matchError: "Could not match items from document",
    userAssignedBranch: "User will be assigned as Branch Manager",
    leaveBlankKeep: "Leave blank to keep current",
    noInventoryData: "No inventory data for this location.",
    noTransactionsFound: "No transactions found",
    accessWarehouseMammal: "Access to Warehouse and Mammal",
    accessMammalOnly: "Access to Mammal operations only",
    fullSystemAccess: "Full System Access",
    confirmDeleteTitle: "Confirm Deletion",
    confirmDeleteUser: "Are you sure you want to delete user",
    confirmDeleteItem: "Are you sure you want to delete item",
    actionIrreversible: "This action cannot be undone.",
    invalidNumber: "Values must be non-negative numbers.",
    stockStatus: "Stock Status",
    allStatuses: "All Statuses",
    globalInventory: "Global Inventory Overview",
    globalInventoryDesc: "View consolidated stock levels across all locations.",
    outgoingApprovals: "Outgoing Approvals",
    outgoingApprovalsDesc: "Requests initiated by Central Managers that need your confirmation before stock is released.",
    confirmOutbound: "Approve & Ship",
    inTransit: "In Transit",
    waitingForSource: "Waiting for Source Approval",
    sourceConfirmed: "Source Confirmed",
    location: "Location",
    notificationCenter: "Notification Center",
    sentItems: "Sent Items",
    incomingRequests: "Incoming Requests",
    accept: "Accept",
    reject: "Reject",
    viewItems: "View Items",
    rejectionReason: "Reason for Rejection",
    rejectionPlaceholder: "Enter reason for returning stock...",
    rejected: "Rejected",
    returnToSource: "Items returned to sender.",
    transferDetails: "Transfer Details",
    transferSummary: "Review items before accepting or rejecting.",
    dailyReport: "Daily Report",
    receivedToday: "Received Today",
    usedToday: "Used Today",
    downloadReport: "Download Report",
    noTransactionsToday: "No transactions recorded today.",
    summary: "Summary",
    reports: "Reports",
    selectDate: "Select Date",
    noDataForDate: "No data available for this date.",
    dailySummary: "Daily Summary",
    totalReceived: "Total Received",
    totalUsed: "Total Used",
    logSheet: "Daily Log Sheet",
    saveChanges: "Save Changes",
    clear: "Clear",
    enterReceived: "Qty Rec",
    enterUsed: "Qty Used",
    updatesPending: "Updates Pending",
    addNote: "Add Note",
    bulkSuccess: "All logs saved successfully",
    tryAdjustingFilters: "Try adjusting your filters or search query.",
    dailyReports: "Daily Reports",
    sortBy: "Sort By",
    sortName: "Name",
    sortQuantity: "Quantity",
    sortDate: "Last Updated",
    ascending: "Ascending",
    descending: "Descending",
    order: "Order",
    view: "View",
    tiles: "Tiles",
    list: "List",
    box: "Box",
    rememberMe: "Keep me logged in for 30 days"
  },
  ar: {
    title: "دوار السعادة",
    subtitle: "نظام إدارة المخزون",
    username: "اسم المستخدم",
    usernamePlaceholder: "أدخل اسم المستخدم",
    password: "كلمة المرور",
    passwordPlaceholder: "أدخل كلمة المرور",
    login: "تسجيل الدخول",
    invalidCredentials: "اسم المستخدم أو كلمة المرور غير صالحة",
    copyright: "© 2024 دوار السعادة. جميع الحقوق محفوظة.",
    selectLocation: "اختر الموقع",
    selectLocationSub: "اختر موقعاً لإدارة المخزون",
    accessInventory: "دخول المخزون",
    warehouse: "المستودع",
    mammal: "المعمل",
    warehouseDesc: "مرفق التخزين الرئيسي للمواد والمواد الخام.",
    mammalDesc: "وحدة الإنتاج والمعالجة.",
    items: "عناصر",
    totalItems: "إجمالي العناصر",
    lowStockAlert: "تنبيه المخزون المنخفض",
    aiInsights: "رؤى الذكاء الاصطناعي",
    searchPlaceholder: "بحث في العناصر...",
    filter: "تصفية",
    addItem: "إضافة عنصر",
    itemName: "اسم العنصر",
    itemNameEn: "الاسم (بالإنجليزي)",
    itemNameAr: "الاسم (بالعربي)",
    itemNameEnPlaceholder: "مثال: Arabica Beans",
    itemNameArPlaceholder: "مثال: بن أرابيكا",
    description: "الوصف",
    descriptionPlaceholder: "أدخل وصفاً مفصلاً للمنتج...",
    category: "الفئة",
    stockLevel: "مستوى المخزون",
    status: "الحالة",
    lastUpdated: "آخر تحديث",
    actions: "إجراءات",
    inStock: "متوفر",
    lowStock: "مخزون منخفض",
    noItemsFound: "لا توجد عناصر تطابق",
    actionNeeded: "إجراء مطلوب",
    restockSuggested: "يقترح إعادة التخزين",
    stockHealthy: "المخزون جيد",
    smartAssistant: "المساعد الذكي",
    poweredBy: "مدعوم من Gemini",
    askAI: "اسأل الذكاء الاصطناعي",
    askPlaceholder: "اسأل عن المخزون...",
    welcomeMessage: "مرحباً! أنا مساعد المخزون لـ",
    howHelp: "كيف يمكنني مساعدتك اليوم؟",
    cantGenerate: "لم أتمكن من إنشاء استجابة في الوقت الحالي.",
    errorOccurred: "عذراً، واجهت خطأ أثناء تحليل المخزون.",
    logout: "تسجيل خروج",
    new: "جديد",
    adminDashboard: "لوحة تحكم المسؤول",
    users: "المستخدمين",
    transactions: "المعاملات",
    createUser: "إنشاء مستخدم",
    editUser: "تعديل المستخدم",
    updateUser: "تحديث المستخدم",
    role: "الدور",
    fullName: "الاسم الكامل",
    saveUser: "حفظ المستخدم",
    cancel: "إلغاء",
    transferStock: "نقل المخزون",
    from: "من",
    to: "إلى",
    quantity: "الكمية",
    submitTransfer: "إرسال النقل",
    selectItem: "اختر العنصر",
    transferSuccess: "تم النقل بنجاح",
    insufficientStock: "مخزون غير كاف",
    date: "التاريخ",
    performedBy: "تم بواسطة",
    delete: "حذف",
    edit: "تعديل",
    viewLogs: "عرض السجلات",
    branch_manager: "مدير فرع",
    warehouse_manager: "مدير",
    mammal_employee: "موظف",
    admin: "مسؤول النظام",
    dailyLog: "السجل اليومي",
    recordUsage: "تسجيل الاستهلاك",
    recordReceive: "تسجيل الاستلام",
    usageDesc: "تسجيل المواد المستهلكة في العمليات اليومية",
    receiveDesc: "تسجيل المواد المستلمة من الموردين",
    submit: "إرسال",
    type: "النوع",
    transfer: "نقل",
    usage: "استهلاك",
    receive: "استلام",
    notes: "ملاحظات (اختياري)",
    notesPlaceholder: "أضف أي تفاصيل إضافية...",
    addToTransfer: "إضافة للقائمة",
    transferList: "العناصر المراد نقلها",
    remove: "إزالة",
    noItemsInList: "لم يتم إضافة عناصر للقائمة بعد.",
    incomingShipments: "الشحنات الواردة",
    confirmReceive: "استلام المخزون",
    pending: "قيد الانتظار",
    completed: "مكتمل",
    cancelled: "ملغى",
    receiveSuccess: "تم استلام المخزون بنجاح",
    incomingDesc: "عناصر منقولة من مواقع أخرى بانتظار تأكيدك.",
    inventory: "المخزون",
    locationType: "نوع الموقع",
    central: "مركزي",
    branch: "فرع",
    branchName: "اسم الفرع",
    branchCode: "كود الفرع",
    branchCodePlaceholder: "مثال: BR001",
    branchNamePlaceholder: "مثال: فرع وسط البلد",
    addItemTitle: "إضافة عنصر جديد",
    initialQty: "الكمية الأولية",
    minThreshold: "الحد الأدنى",
    unit: "الوحدة",
    unitPlaceholder: "مثال: كغ، قطعة، صندوق",
    thresholdDesc: "تنبيه عندما ينخفض المخزون عن هذا المقدار",
    manageLocation: "إدارة المخزون",
    currentStock: "قائمة المخزون الحالي",
    exportPDF: "تصدير PDF",
    exportExcel: "تصدير Excel",
    centralLocations: "المواقع المركزية",
    branchLocations: "الفروع",
    branches: "الفروع",
    confirm: "تأكيد",
    used: "مستخدم",
    smartUpload: "تحميل ذكي",
    confirmTransferPdf: "تأكيد النقل (من PDF)",
    noOtherLocations: "لا توجد مواقع أخرى متاحة",
    qtyGreaterZero: "يجب أن تكون الكمية أكبر من 0",
    matchError: "تعذر مطابقة العناصر من المستند",
    userAssignedBranch: "سيتم تعيين المستخدم كمدير فرع",
    leaveBlankKeep: "اتركه فارغاً للاحتفاظ بكلمة المرور الحالية",
    noInventoryData: "لا توجد بيانات مخزون لهذا الموقع.",
    noTransactionsFound: "لم يتم العثور على معاملات",
    accessWarehouseMammal: "الدخول للمستودع والمعمل",
    accessMammalOnly: "الدخول لعمليات المعمل فقط",
    fullSystemAccess: "دخول كامل للنظام",
    confirmDeleteTitle: "تأكيد الحذف",
    confirmDeleteUser: "هل أنت متأكد من حذف المستخدم",
    confirmDeleteItem: "هل أنت متأكد من حذف العنصر",
    actionIrreversible: "هذا الإجراء لا يمكن التراجع عنه.",
    invalidNumber: "يجب أن تكون القيم أرقاماً غير سالبة.",
    stockStatus: "حالة المخزون",
    allStatuses: "جميع الحالات",
    globalInventory: "نظرة عامة على المخزون العالمي",
    globalInventoryDesc: "عرض مستويات المخزون الموحدة عبر جميع المواقع.",
    outgoingApprovals: "الموافقات الصادرة",
    outgoingApprovalsDesc: "الطلبات التي بدأها المديرون المركزيون والتي تحتاج إلى تأكيدك قبل إصدار المخزون.",
    confirmOutbound: "تأكيد الشحن",
    inTransit: "في الطريق",
    waitingForSource: "بانتظار موافقة المصدر",
    sourceConfirmed: "تم تأكيد المصدر",
    location: "الموقع",
    notificationCenter: "مركز التنبيهات",
    sentItems: "العناصر المرسلة",
    incomingRequests: "الطلبات الواردة",
    accept: "قبول",
    reject: "رفض",
    viewItems: "عرض العناصر",
    rejectionReason: "سبب الرفض",
    rejectionPlaceholder: "أدخل سبب إعادة المخزون...",
    rejected: "مرفوض",
    returnToSource: "تمت إعادة العناصر إلى المرسل.",
    transferDetails: "تفاصيل النقل",
    transferSummary: "راجع العناصر قبل القبول أو الرفض.",
    dailyReport: "التقرير اليومي",
    receivedToday: "استلم اليوم",
    usedToday: "استخدم اليوم",
    downloadReport: "تحميل التقرير",
    noTransactionsToday: "لم يتم تسجيل أي معاملات اليوم.",
    summary: "ملخص",
    reports: "التقارير",
    selectDate: "اختر التاريخ",
    noDataForDate: "لا توجد بيانات لهذا التاريخ.",
    dailySummary: "الملخص اليومي",
    totalReceived: "إجمالي المستلم",
    totalUsed: "إجمالي المستخدم",
    logSheet: "ورقة السجل اليومي",
    saveChanges: "حفظ التغييرات",
    clear: "مسح",
    enterReceived: "كمية الاستلام",
    enterUsed: "كمية الاستهلاك",
    updatesPending: "تحديثات معلقة",
    addNote: "إضافة ملاحظة",
    bulkSuccess: "تم حفظ جميع السجلات بنجاح",
    tryAdjustingFilters: "حاول تعديل خيارات التصفية أو البحث.",
    dailyReports: "التقارير اليومية",
    sortBy: "ترتيب حسب",
    sortName: "الاسم",
    sortQuantity: "الكمية",
    sortDate: "آخر تحديث",
    ascending: "تصاعدي",
    descending: "تنازلي",
    order: "الترتيب",
    view: "عرض",
    tiles: "مربعات",
    list: "قائمة",
    box: "صندوق",
    rememberMe: "تذكرني لمدة 30 يوماً"
  }
};